# This file may be used to create an environment using:
# $   conda create --n domain2go_env
# $   conda activate domain2go_env
# $   conda env update --file requirements.yml


name: domain2go_env
channels:
  - anaconda
  - defaults
  - conda-forge
dependencies:
  - pandas==1.3.2
  - dask==2022.2.1
  - numpy==1.20.3
  - scipy==1.7.1
  - requests==2.31.0
  - intervaltree==3.1.0
  - pip:
    - biopython==1.81